export const materiaPrima = [
  {
    id: 1,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 2,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Proceso",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 3,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 4,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Proceso",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 5,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 6,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Proceso",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },

  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "-----------",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
  {
    id: 7,
    nombre: "Botella",
    tipo: "PET",
    cantidad: 30,
    estado: "Finalizado",
    FIProduccion: "10-12-2023",
    FFProduccion: "04-04-2024",
  },
];
