export const materiaPrima = [
  {
    NroPedido: 1,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 2,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 3,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 4,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 5,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 6,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 7,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 8,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 9,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 10,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Pendientes",
  },
  {
    NroPedido: 11,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Penidente",
  },
  {
    NroPedido: 12,
    Fecha: "08/06/2022",
    Cliente: "Juan Lopez",
    Producto: "Botella",
    Cantidad: 30,
    Estado: "Penidente",
  },
];
