export const materiaPrima = [
    {
        id: 1,
        Sector: "A",
        Categoria: 'Pet',
        Cantidad: 10,
        Peso: 30,
        Fecha: "10-05-2023",
    },
    {
        id: 2,
        Sector: "A",
        Categoria: 'HDPE',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023"
    },
    {
        id: 3,
        Sector: "A",
        Categoria: 'PVC',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 4,
        Sector: "A",
        Categoria: 'LDPE',
        Cantidad: 10,
        Peso: 5,
        Fecha: "10-05-2023",
    },
    {
        id: 5,
        Sector: "A",
        Categoria: 'PS',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 6,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 7,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 8,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 9,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 10,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 11,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },
    {
        id: 12,
        Sector: "A",
        Categoria: 'O',
        Cantidad: 10,
        Peso: 3,
        Fecha: "10-05-2023",
    },

];







/*
    id: 1,
    Categoria: 'Pet',
    cantidad: 10,
    Peso: 30,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 2,
    Categoria: 'HDPE',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023"
},
{
    id: 3,
    Categoria: 'PVC',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 4,
    Categoria: 'LDPE',
    cantidad: 10,
    Peso: 5,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 5,
    Categoria: 'PS',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},

];*/

